- adapter-bukkit/src/main/java/net/kyori/text/adapter/bukkit/CraftBukkitAdapter.java
- adapter-bukkit/src/main/java/net/kyori/text/adapter/bukkit/SpigotAdapter.java
fixes:
```
[14:09:52 INFO]: Luck issued server command: /lp help
[14:09:52 ERROR]: [LuckPerms] Exception whilst executing command: [help]
[14:09:52 WARN]: java.lang.NoClassDefFoundError: com/google/gson/internal/bind/TreeTypeAdapter
[14:09:52 WARN]:        at me.lucko.luckperms.lib.text.adapter.bukkit.SpigotAdapter.bind(SpigotAdapter.java:60)
[14:09:52 WARN]:        at me.lucko.luckperms.lib.text.adapter.bukkit.SpigotAdapter.<clinit>(SpigotAdapter.java:47)
[14:09:52 WARN]:        at me.lucko.luckperms.lib.text.adapter.bukkit.TextAdapter0.pickAdapters(TextAdapter.java:69)
[14:09:52 WARN]:        at me.lucko.luckperms.lib.text.adapter.bukkit.TextAdapter0.<clinit>(TextAdapter.java:64)
[14:09:52 WARN]:        at me.lucko.luckperms.lib.text.adapter.bukkit.TextAdapter.sendComponent(TextAdapter.j …
```
> Add support for older Gson versions in SpigotAdapter

- adapter-bungeecord/src/main/java/net/kyori/text/adapter/bungeecord/TextAdapter.java
Fixes https://github.com/lucko/LuckPerms/issues/1362
An alternative would be to change the adapter to only accept `ProxiedPlayer` parameters.
> Implement #toLegacyText for sending components to the BungeeCord console

- platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/BukkitFacet.java
- platform-viaversion/build.gradle
- platform-viaversion/src/main/java/net/kyori/adventure/platform/viaversion/ViaFacet.java
I was going to open this later (or wait for you to do it), but a few people have complained since we generally advise people to stay on dev builds atm. The License split we had made a breaking change to the ViaManager class (now interface) necessary.
`Via.getAPI().getServerVersion().lowestSupportedVersion()` will return the same exact value that `ProtocolRegistry.SERVER_PROTOCOL` gave (still gives, but is deprecated).
> Update ViaVersion dependency

- platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/BukkitAudience.java
- platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/BukkitFacet.java
- platform-viaversion/build.gradle
- platform-viaversion/src/main/java/net/kyori/adventure/platform/viaversion/ViaFacet.java
Updated ViaVersion... *again* (at least without version clashes as with the first pr). This time you should actually wait 1-2 weeks before merging this (with people actually updating / no more breaks happening, even if unlikely). I also didn't have time to test this pr yet, but I'm opening this anyways so it's on your radar.
Note on the `ProtocolInfo` null check in `findProtocol(V)`: It's no longer nullable, and `getProtocolVersion()` returns -1 before finalized (as previously already), so the check is just removed and the rest left as is.
> Update ViaVersion to 4.0.0 repackage

- platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/BukkitAudiencesImpl.java
- platform-bungeecord/src/main/java/net/kyori/adventure/platform/bungeecord/BungeeAudiencesImpl.java
- platform-spongeapi/src/main/java/net/kyori/adventure/platform/spongeapi/SpongeAudiencesImpl.java
Added `[...]Audiences.clear()` and `[...]Audiences.clear(Plugin)` to all three audiences. This will remove the audience from the static cache. This functionality may be needed by test environments.
This is related to [this request on discord](https://discord.com/channels/319355592605040642/420342659115122688/903015403113033749).
> feat(platform): add clear methods to remove the audience provider cache

- platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/CraftBukkitFacet.java
- platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/MinecraftReflection.java
Fixes #66 
```
[18:01:54] [Server thread/INFO]: Skipped facet: net.kyori.adventure.platform.bukkit.BukkitAudience$$Lambda$4769/0x0000000801aa9440
[18:01:54] [Server thread/INFO]: Added facet: net.kyori.adventure.platform.bukkit.CraftBukkitFacet$Chat@374caafe
[18:01:54] [Server thread/INFO]: Added facet: net.kyori.adventure.platform.bukkit.BukkitFacet$Chat@289b4bff
[18:01:54] [Server thread/INFO]: Skipped facet: net.kyori.adventure.platform.bukkit.BukkitAudience$$Lambda$4782/0x0000000801ab0298
[18:01:54] [Server thread/INFO]: Skipped facet: net.kyori.adventure.platform.bukkit.BukkitAudience$$Lambda$4783/0x0000000801ab04b8
[18:01:54] [Server thread/INFO]: Added facet: net.kyori.adventure.platform.bukkit.CraftBukkitFacet$ActionBar_1_17@167e02b3
[18:01:54] [Server thread/INFO]: Skipped facet: …
```
> Add 1.18 support

- platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/CraftBukkitFacet.java
Fixes https://github.com/KyoriPowered/adventure-platform/issues/92
> fix: CraftBukkit Chat facet for 1.19

- platform-viaversion/build.gradle
- platform-viaversion/src/main/java/net/kyori/adventure/platform/viaversion/ViaFacet.java
Use the correct type when writing components as jsonelements instead of strings; this didn't cause any issue before because there were no handlers in Via trying to get the expected component type, but one has been added in 1.19 protocol transformation, causing an error when sending chat packets to 1.19+ clients.
The `majorVersion` method on ViaAPI was added in 4.0.2 (a long while ago), now being checked to make sure this doesn't break on 5.x in case API changes a lot again.
Unrelated to the issue, but this also uses `PacketWrapper.scheduleSend` instead of `send` to schedule this to the netty thread instead of any random thread this may be called on
> Fix ViaFacet component type

- platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/CraftBukkitFacet.java
Fixes https://github.com/KyoriPowered/adventure-platform/issues/97
1.19 added a long type seed to the constructors for the entity packet and custom packet.
> fix: CraftBukkit EntitySound for 1.19+

- platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/BukkitAudience.java
- platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/BukkitFacet.java
- platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/CraftBukkitAccess.java
- platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/CraftBukkitFacet.java
- platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/MinecraftReflection.java
- platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/SpigotFacet.java
- platform-bungeecord/src/main/java/net/kyori/adventure/platform/bungeecord/BungeeFacet.java
- platform-facet/src/main/java/net/kyori/adventure/platform/facet/Facet.java
- platform-facet/src/main/java/net/kyori/adventure/platform/facet/FacetAudience.java
- platform-spongeapi/src/main/java/net/kyori/adventure/platform/spongeapi/SpongeFacet.java
- platform-viaversion/src/main/java/net/kyori/adventure/platform/viaversion/ViaFacet.java
So far this has just added handling for disguised messages, nothing for the signed message api yet, not sure if that is really needed. Disguised messages I think should be in here.
> 1.19.3 chat for bukkit

- platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/CraftBukkitAccess.java
- platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/CraftBukkitFacet.java
Small fix for 1.19.4 chat. Main difference was a method was moved from ServerLevel to Level and so a small change needed to be added to account for that.
> fix: 1.19.4 bound chat types

- platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/CraftBukkitFacet.java
In 1.20.2, `send(Packet)` was moved from `ServerGamePacketListenerImpl` to its new superclass `ServerCommonPacketListenerImpl`.
Because `getDeclaredMethods` doesn't return methods defined in superclasses, `CraftBukkitFacet` didn't work at all.
Changed `MinecraftReflection#searchMethod` to use `getMethods` instead of `getDeclaredMethods`.
> Fix CraftBukkitFacet on 1.20.2

- platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/CraftBukkitFacet.java
- platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/MinecraftComponentSerializer.java
`ChatSerializer` no longer implements `JsonDeserializer`, it uses codecs instead.
`MinecraftComponentSerializer` expects the serialization methods to be in a subclass which implements `JsonDeserializer`.
This change makes it look for these methods in all subclasses instead of just that one.
Additionally, it makes it look for serialization methods which use `JsonElement` instead of `String`.
The previous approach of using `MC_TEXT_GSON` to avoid converting via `String` doesn't work in 1.20.3, `ChatSerializer` no longer provides a Gson object with the type adapter.
> Fix MinecraftComponentSerializer on 1.20.3

- gradle.properties
- Fix root URL
- ~~Update Paper javadocs (apparently javadocs before 1.17 were removed)~~
> Fix javadoc generation

- platform-bungeecord/build.gradle
- platform-bungeecord/src/main/java/net/kyori/adventure/platform/bungeecord/BungeeFacet.java
- platform-bungeecord/src/main/java/net/kyori/adventure/platform/bungeecord/BungeeReflection.java
- settings.gradle
**Description**
This Pull Request updates the method for changing the BossBar title to use `TextComponent.fromArray(BaseComponent[])` instead of `ComponentSerializer.toString(BaseComponent[])`. 
Additionally, it adds the **minecraft-libraries** repository because the new **bungeecord-api** depends on `com.mojang:brigadier`, which requires **minecraft-libraries**.
Related Issue: #152
> BungeeCord: BossBar compatibilty with BungeeCord 1.20-R0.2 and newer

- platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/BukkitAudience.java
- platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/BukkitAudiencesImpl.java
- platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/BukkitFacet.java
The pull request sets the client locale for Player audiences in the adventure-platform-bukkit module.
Until now, the client locale was only correct if the player changed their locale via settings while playing on the server.
> Set player locale when creating Audience

- platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/MinecraftComponentSerializer.java
Fix it with more reflection, maybe shading/relocating gson is not a good idea, but someone will do it
> Fixed MinecraftComponentSerializer not working due to relocation

- platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/CraftBukkitAccess.java
- platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/CraftBukkitFacet.java
Attempt to use a static factory method if the `ResourceLocation` constructor is not public.
Fixes #186
> Fix removed ResourceLocation constructor

- platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/BukkitAudiencesImpl.java
- platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/BukkitFacet.java
- settings.gradle
After #160 our server has not had locales working. Prior to that our server impl already worked because it sent the locale change event right after a player logged in (once the client sent their settings packet), and the change introduced broke it as our server implementation's Player#getLocale returns a Locale, not a String.
This seems like a pretty reasonable thing to support.
For reference:
<https://github.com/Electroid/SportPaper/blob/main/patches/api/0084-Improve-locale-API-and-add-methods-for-translating-c.patch#L150>
Additionally i've removed the forgotten `registerLocaleEvent` method, that seems to have been left behind but not used anywhere anymore.
> Support getLocale returning a Locale

- platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/MinecraftComponentSerializer.java
This PR adds support for Minecraft 1.21.6 by integrating the new `ComponentSerialization.CODEC` for component serialization, while preserving compatibility with older versions.
> Bukkit - Update MinecraftComponentSerializer for 1.21.6/7
